// AUTO-GENERATED FROM JSDOC. DO NOT EDIT.
export declare class mxConnectionHandler {
  constructor(graph: unknown, factoryMethod: number);
  insertEdge(parent: unknown, id: number, value: unknown, source: unknown, target: unknown, style: number): unknown;
  isEnabled(...args: any[]): unknown;
  setEnabled(enabled: boolean): void;
  isInsertBefore(edge: unknown, source: unknown, target: unknown, evt: unknown, dropTarget: unknown): unknown;
  isCreateTarget(evt: unknown): unknown;
  setCreateTarget(value: unknown): void;
  createShape(...args: any[]): unknown;
  init(...args: any[]): unknown;
  isConnectableCell(cell: unknown): unknown;
  createMarker(...args: any[]): unknown;
  start(state: unknown, x: number, y: number, edgeState: unknown): void;
  isConnecting(...args: any[]): unknown;
  isValidSource(cell: unknown, me: unknown): unknown;
  isValidTarget(cell: unknown): unknown;
  validateConnection(source: unknown, target: unknown): unknown;
  getConnectImage(state: unknown): unknown;
  isMoveIconToFrontForState(state: unknown): unknown;
  createIcons(state: unknown): unknown;
  redrawIcons(icons: unknown, state: unknown): void;
  getIconPosition(icon: unknown, state: unknown): unknown;
  destroyIcons(...args: any[]): void;
  isStartEvent(me: unknown): unknown;
  mouseDown(sender: unknown, me: unknown): unknown;
  isImmediateConnectSource(state: unknown): unknown;
  createEdgeState(me: unknown): unknown;
  isOutlineConnectEvent(me: unknown): unknown;
  updateCurrentState(me: unknown, point: unknown): void;
  isCellEnabled(cell: unknown): unknown;
  convertWaypoint(point: unknown): unknown;
  snapToPreview(me: unknown, point: unknown): unknown;
  mouseMove(sender: unknown, me: unknown): unknown;
  updateEdgeState(current: unknown, constraint: unknown): void;
  getTargetPerimeterPoint(state: unknown, me: unknown): unknown;
  getSourcePerimeterPoint(state: unknown, next: number, me: unknown): unknown;
  updateIcons(state: unknown, icons: unknown, me: unknown): void;
  isStopEvent(me: unknown): unknown;
  addWaypointForEvent(me: unknown): void;
  checkConstraints(c1: unknown, c2: unknown): unknown;
  mouseUp(sender: unknown, me: unknown): unknown;
  reset(...args: any[]): void;
  drawPreview(...args: any[]): unknown;
  updatePreview(valid: number): void;
  getEdgeColor(valid: number): unknown;
  getEdgeWidth(valid: number): unknown;
  connect(source: unknown, target: unknown, evt: unknown, dropTarget: unknown): unknown;
  selectCells(edge: unknown, target: unknown): unknown;
  createTargetVertex(evt: unknown, source: unknown): unknown;
  getAlignmentTolerance(evt: unknown): unknown;
  createEdge(value: unknown, source: unknown, target: unknown, style: number): unknown;
  destroy(...args: any[]): void;
}