// AUTO-GENERATED FROM JSDOC. DO NOT EDIT.
export declare class mxEdgeHandler {
  constructor(state: unknown);
  init(...args: any[]): unknown;
  createCustomHandles(...args: any[]): unknown;
  isVirtualBendsEnabled(evt: unknown): unknown;
  isCellEnabled(cell: unknown): unknown;
  isAddPointEvent(evt: unknown): unknown;
  isRemovePointEvent(evt: unknown): unknown;
  getSelectionPoints(state: unknown): unknown;
  createParentHighlightShape(bounds: unknown): unknown;
  createSelectionShape(points: unknown): unknown;
  getSelectionColor(...args: any[]): unknown;
  getSelectionStrokeWidth(...args: any[]): unknown;
  isSelectionDashed(...args: any[]): unknown;
  isConnectableCell(cell: unknown): unknown;
  getCellAt(x: number, y: number): unknown;
  createMarker(...args: any[]): unknown;
  validateConnection(source: unknown, target: unknown): unknown;
  createBends(...args: any[]): unknown;
  createVirtualBends(...args: any[]): unknown;
  isHandleEnabled(index: number): unknown;
  isHandleVisible(index: number): unknown;
  createHandleShape(index: number): unknown;
  createLabelHandleShape(...args: any[]): unknown;
  initBend(bend: unknown, dblClick: unknown): unknown;
  getHandleForEvent(me: unknown): unknown;
  isAddVirtualBendEvent(me: unknown): unknown;
  isCustomHandleEvent(me: unknown): unknown;
  mouseDown(sender: unknown, me: unknown): unknown;
  start(x: number, y: number, index: number): void;
  clonePreviewState(point: unknown, terminal: unknown): unknown;
  getSnapToTerminalTolerance(...args: any[]): unknown;
  updateHint(me: unknown, point: unknown): void;
  removeHint(...args: any[]): void;
  roundLength(length: number): unknown;
  isSnapToTerminalsEvent(me: unknown): unknown;
  getPointForEvent(me: unknown): unknown;
  getPreviewTerminalState(me: unknown): unknown;
  getPreviewPoints(pt: unknown, me: unknown): unknown;
  isOutlineConnectEvent(me: unknown): unknown;
  updatePreviewState(edge: unknown, point: unknown, terminalState: unknown, me: unknown, outline: unknown): void;
  mouseMove(sender: unknown, me: unknown): unknown;
  mouseUp(sender: unknown, me: unknown): unknown;
  reset(...args: any[]): void;
  setPreviewColor(color: string): void;
  convertPoint(point: unknown, gridEnabled: number): unknown;
  moveLabel(edgeState: unknown, x: number, y: number): unknown;
  connect(edge: unknown, terminal: unknown, isSource: boolean, isClone: boolean, me: unknown): unknown;
  changeTerminalPoint(edge: unknown, point: unknown, isSource: boolean, clone: unknown): unknown;
  changePoints(edge: unknown, points: unknown, clone: unknown): unknown;
  addPoint(state: unknown, evt: unknown): void;
  addPointAt(state: unknown, x: number, y: number): void;
  removePoint(state: unknown, index: number): void;
  getHandleFillColor(index: number): unknown;
  redraw(ignoreHandles: unknown): void;
  redrawHandles(...args: any[]): void;
  isCustomHandleVisible(handle: unknown): unknown;
  setHandlesVisible(visible: boolean): void;
  redrawInnerBends(p0: unknown, pe: unknown): void;
  checkLabelHandle(b: unknown): unknown;
  drawPreview(...args: any[]): unknown;
  refresh(...args: any[]): void;
  destroyBends(bends: unknown): void;
  destroy(...args: any[]): void;
}