// AUTO-GENERATED FROM JSDOC. DO NOT EDIT.
export declare class mxEditor {
  constructor(config: unknown);
  isModified(...args: any[]): unknown;
  setModified(value: unknown): void;
  addActions(...args: any[]): void;
  configure(node: unknown): unknown;
  resetFirstTime(...args: any[]): void;
  resetHistory(...args: any[]): void;
  addAction(actionname: string, funct: unknown): void;
  execute(actionname: string, cell: unknown, evt: unknown): unknown;
  addTemplate(name: string, template: unknown): void;
  getTemplate(name: string): unknown;
  createGraph(...args: any[]): unknown;
  createSwimlaneManager(graph: unknown): unknown;
  createLayoutManager(graph: unknown): unknown;
  setGraphContainer(container: unknown): void;
  installDblClickHandler(graph: unknown): unknown;
  installUndoHandler(graph: unknown): unknown;
  installDrillHandler(graph: unknown): unknown;
  installChangeHandler(graph: unknown): unknown;
  installInsertHandler(graph: unknown): unknown;
  createDiagramLayout(...args: any[]): unknown;
  createSwimlaneLayout(...args: any[]): unknown;
  createToolbar(...args: any[]): unknown;
  setToolbarContainer(container: unknown): void;
  setStatusContainer(container: unknown): void;
  setStatus(message: string): void;
  setTitleContainer(container: unknown): void;
  treeLayout(cell: unknown, horizontal: unknown): unknown;
  getTitle(...args: any[]): unknown;
  getRootTitle(...args: any[]): unknown;
  undo(...args: any[]): unknown;
  redo(...args: any[]): unknown;
  groupCells(...args: any[]): unknown;
  createGroup(...args: any[]): unknown;
  open(filename: string): unknown;
  readGraphModel(node: unknown): unknown;
  save(url: string, linefeed: unknown): unknown;
  postDiagram(url: string, data: unknown): unknown;
  writeGraphModel(linefeed: unknown): unknown;
  getUrlPost(...args: any[]): unknown;
  getUrlImage(...args: any[]): unknown;
  swapStyles(first: unknown, second: unknown): unknown;
  showProperties(cell: unknown): void;
  isPropertiesVisible(...args: any[]): unknown;
  createProperties(cell: unknown): unknown;
  hideProperties(...args: any[]): void;
  showTasks(...args: any[]): void;
  refreshTasks(div: unknown): void;
  createTasks(div: unknown): unknown;
  showHelp(tasks: unknown): void;
  showOutline(...args: any[]): void;
  setMode(modename: string): void;
  createPopupMenu(menu: unknown, cell: unknown, evt: unknown): unknown;
  createEdge(source: unknown, target: unknown): unknown;
  getEdgeStyle(...args: any[]): unknown;
  consumeCycleAttribute(cell: unknown): unknown;
  cycleAttribute(cell: unknown): unknown;
  addVertex(parent: unknown, vertex: number, x: number, y: number): void;
  destroy(...args: any[]): void;
}