// AUTO-GENERATED FROM JSDOC. DO NOT EDIT.
export declare class mxGraph {
  constructor(container: unknown, model: unknown, renderHint: unknown, stylesheet: number);
  getTooltipForCell(cell: unknown): string;
  init(container: unknown): unknown;
  createHandlers(...args: any[]): unknown;
  createTooltipHandler(...args: any[]): unknown;
  createSelectionCellsHandler(...args: any[]): unknown;
  createConnectionHandler(...args: any[]): unknown;
  createGraphHandler(...args: any[]): unknown;
  createPanningHandler(...args: any[]): unknown;
  createPopupMenuHandler(...args: any[]): unknown;
  createSelectionModel(...args: any[]): unknown;
  createStylesheet(...args: any[]): unknown;
  createGraphView(...args: any[]): unknown;
  createCellRenderer(...args: any[]): unknown;
  createCellEditor(...args: any[]): unknown;
  getModel(...args: any[]): unknown;
  getView(...args: any[]): unknown;
  getStylesheet(...args: any[]): unknown;
  setStylesheet(stylesheet: number): void;
  getSelectionModel(...args: any[]): unknown;
  setSelectionModel(selectionModel: unknown): void;
  getSelectionCellsForChanges(changes: unknown, ignoreFn: unknown): boolean;
  graphModelChanged(changes: unknown): unknown;
  updateSelection(...args: any[]): void;
  processChange(change: unknown): unknown;
  removeStateForCell(cell: unknown): void;
  addCellOverlay(cell: unknown, overlay: number): void;
  getCellOverlays(cell: unknown): unknown;
  removeCellOverlay(cell: unknown, overlay: number): void;
  removeCellOverlays(cell: unknown): void;
  clearCellOverlays(cell: unknown): void;
  setCellWarning(cell: unknown, warning: unknown, img: unknown, isSelect: boolean): void;
  startEditing(evt: unknown): void;
  startEditingAtCell(cell: unknown, evt: unknown): void;
  getEditingValue(cell: unknown, evt: unknown): string;
  stopEditing(cancel: unknown): void;
  labelChanged(cell: unknown, value: unknown, evt: unknown): unknown;
  cellLabelChanged(cell: unknown, value: unknown, autoSize: number): unknown;
  escape(evt: unknown): unknown;
  click(me: unknown): unknown;
  isSiblingSelected(cell: unknown): boolean;
  dblClick(evt: unknown, cell: unknown): unknown;
  tapAndHold(me: unknown): unknown;
  scrollPointToVisible(x: number, y: number, extend: number, border: unknown): unknown;
  createPanningManager(...args: any[]): unknown;
  getBorderSizes(...args: any[]): unknown;
  getPreferredPageSize(bounds: unknown, width: number, height: number): unknown;
  fit(border: unknown, keepOrigin: unknown, margin: unknown, enabled: boolean, ignoreWidth: number, ignoreHeight: number, maxHeight: number): unknown;
  sizeDidChange(...args: any[]): unknown;
  doResizeContainer(width: number, height: number): unknown;
  updatePageBreaks(visible: boolean, width: number, height: number): void;
  getCurrentCellStyle(cell: unknown, ignoreState: unknown): unknown;
  getCellStyle(cell: unknown): unknown;
  postProcessCellStyle(style: number): unknown;
  setCellStyle(style: number, cells: unknown): void;
  toggleCellStyle(key: number, defaultValue: unknown, cell: unknown): unknown;
  toggleCellStyles(key: number, defaultValue: unknown, cells: unknown): unknown;
  setCellStyles(key: number, value: unknown, cells: unknown): void;
  toggleCellStyleFlags(key: number, flag: boolean, cells: unknown): unknown;
  setCellStyleFlags(key: number, flag: boolean, value: unknown, cells: unknown): void;
  alignCells(align: unknown, cells: unknown, param: unknown): unknown;
  flipEdge(edge: unknown): unknown;
  addImageBundle(bundle: unknown): void;
  removeImageBundle(bundle: unknown): void;
  getImageFromBundles(key: number): unknown;
  orderCells(back: unknown, cells: unknown): unknown;
  cellsOrdered(cells: unknown, back: unknown): unknown;
  groupCells(group: unknown, border: unknown, cells: unknown): unknown;
  getCellsForGroup(cells: unknown): unknown;
  getBoundsForGroup(group: unknown, children: unknown, border: unknown): unknown;
  createGroupCell(cells: unknown): unknown;
  ungroupCells(cells: unknown): unknown;
  removeCellsAfterUngroup(cells: unknown): void;
  removeCellsFromParent(cells: unknown): void;
  updateGroupBounds(cells: unknown, border: unknown, moveGroup: unknown, topBorder: number, rightBorder: number, bottomBorder: number, leftBorder: number): void;
  getBoundingBox(cells: unknown): unknown;
  cloneCell(cell: unknown, allowInvalidEdges: number, mapping: unknown, keepPosition: unknown): unknown;
  cloneCells(cells: unknown, allowInvalidEdges: number, mapping: unknown, keepPosition: unknown): unknown;
  insertVertex(parent: unknown, id: number, value: unknown, x: number, y: number, width: number, height: number, style: number, relative: unknown): unknown;
  createVertex(parent: unknown, id: number, value: unknown, x: number, y: number, width: number, height: number, style: number, relative: unknown): unknown;
  insertEdge(parent: unknown, id: number, value: unknown, source: unknown, target: unknown, style: number): unknown;
  createEdge(parent: unknown, id: number, value: unknown, source: unknown, target: unknown, style: number): unknown;
  addEdge(edge: unknown, parent: unknown, source: unknown, target: unknown, index: number): void;
  addCell(cell: unknown, parent: unknown, index: number, source: unknown, target: unknown): void;
  addCells(cells: unknown, parent: unknown, index: number, source: unknown, target: unknown, absolute: unknown): void;
  cellsAdded(cells: unknown, parent: unknown, index: number, source: unknown, target: unknown, absolute: unknown, constrain: unknown, extend: number): unknown;
  autoSizeCell(cell: unknown, recurse: unknown): unknown;
  removeCells(cells: unknown, includeEdges: unknown): void;
  cellsRemoved(cells: unknown): unknown;
  splitEdge(edge: unknown, cells: unknown, newEdge: unknown, dx: number, dy: number, x: number, y: number, parent: unknown): unknown;
  toggleCells(show: boolean, cells: unknown, includeEdges: unknown): unknown;
  cellsToggled(cells: unknown, show: boolean): unknown;
  foldCells(collapse: unknown, recurse: unknown, cells: unknown, checkFoldable: unknown, evt: unknown): unknown;
  cellsFolded(cells: unknown, collapse: unknown, recurse: unknown, checkFoldable: unknown): unknown;
  swapBounds(cell: unknown, willCollapse: unknown): unknown;
  updateAlternateBounds(cell: unknown, geo: unknown, willCollapse: unknown): void;
  addAllEdges(cells: unknown): void;
  getAllEdges(cells: unknown): unknown;
  updateCellSize(cell: unknown, ignoreChildren: unknown): void;
  cellSizeUpdated(cell: unknown, ignoreChildren: unknown): unknown;
  getPreferredSizeForCell(cell: unknown, textWidth: number): unknown;
  resizeCell(cell: unknown, bounds: unknown, recurse: unknown): unknown;
  resizeCells(cells: unknown, bounds: unknown, recurse: unknown): unknown;
  cellsResized(cells: unknown, bounds: unknown, recurse: unknown): unknown;
  cellResized(cell: unknown, bounds: unknown, ignoreRelative: unknown, recurse: unknown): unknown;
  resizeChildCells(cell: unknown, newGeo: unknown): unknown;
  constrainChildCells(cell: unknown): unknown;
  scaleCell(cell: unknown, dx: number, dy: number, recurse: unknown): unknown;
  extendParent(cell: unknown): unknown;
  importCells(cells: unknown, dx: number, dy: number, target: unknown, evt: unknown, mapping: unknown): unknown;
  moveCells(cells: unknown, dx: number, dy: number, clone: unknown, target: unknown, evt: unknown, mapping: unknown): unknown;
  cellsMoved(cells: unknown, dx: number, dy: number, disconnect: boolean, constrain: unknown, extend: number): unknown;
  translateCell(cell: unknown, dx: number, dy: number): unknown;
  getCellContainmentArea(cell: unknown): unknown;
  getMaximumGraphBounds(...args: any[]): unknown;
  constrainChild(cell: unknown, sizeFirst: number): unknown;
  resetEdges(cells: unknown): void;
  resetEdge(edge: unknown): void;
  getOutlineConstraint(point: unknown, terminalState: unknown, me: unknown): unknown;
  getAllConnectionConstraints(terminal: unknown, source: unknown): unknown;
  getConnectionConstraint(edge: unknown, terminal: unknown, source: unknown): unknown;
  setConnectionConstraint(edge: unknown, terminal: unknown, source: unknown, constraint: unknown): void;
  getConnectionPoint(vertex: number, constraint: unknown, round: unknown): unknown;
  connectCell(edge: unknown, terminal: unknown, source: unknown, constraint: unknown): unknown;
  cellConnected(edge: unknown, terminal: unknown, source: unknown, constraint: unknown): unknown;
  disconnectGraph(cells: unknown): unknown;
  getCurrentRoot(...args: any[]): unknown;
  getTranslateForRoot(cell: unknown): unknown;
  isPort(cell: unknown): boolean;
  getTerminalForPort(cell: unknown, source: unknown): unknown;
  getChildOffsetForCell(cell: unknown): unknown;
  enterGroup(cell: unknown): boolean;
  exitGroup(...args: any[]): unknown;
  home(...args: any[]): unknown;
  isValidRoot(cell: unknown): boolean;
  getGraphBounds(...args: any[]): unknown;
  getCellBounds(cell: unknown, includeEdges: unknown, includeDescendants: unknown): unknown;
  getBoundingBoxFromGeometry(cells: unknown, includeEdges: unknown): unknown;
  refresh(cell: unknown): void;
  snap(value: unknown): unknown;
  snapDelta(delta: unknown, bounds: unknown, ignoreGrid: number, ignoreHorizontal: unknown, ignoreVertical: unknown): unknown;
  panGraph(dx: number, dy: number): unknown;
  zoomIn(...args: any[]): unknown;
  zoomOut(...args: any[]): unknown;
  zoomActual(...args: any[]): unknown;
  zoomTo(scale: number, center: unknown): unknown;
  center(horizontal: unknown, vertical: unknown, cx: number, cy: number): unknown;
  zoom(factor: unknown, center: unknown): unknown;
  zoomToRect(rect: unknown): unknown;
  scrollCellToVisible(cell: unknown, center: unknown): unknown;
  scrollRectToVisible(rect: unknown): unknown;
  getCellGeometry(cell: unknown): unknown;
  isCellVisible(cell: unknown): boolean;
  isCellCollapsed(cell: unknown): boolean;
  isCellConnectable(cell: unknown): boolean;
  isOrthogonal(edge: unknown): boolean;
  isLoop(state: unknown): boolean;
  isCloneEvent(evt: unknown): boolean;
  isTransparentClickEvent(evt: unknown): boolean;
  isToggleEvent(evt: unknown): boolean;
  isGridEnabledEvent(evt: unknown): boolean;
  isConstrainedEvent(evt: unknown): boolean;
  isIgnoreTerminalEvent(evt: unknown): boolean;
  validationAlert(message: string): unknown;
  isEdgeValid(edge: unknown, source: unknown, target: unknown): unknown;
  getEdgeValidationError(edge: unknown, source: unknown, target: unknown): unknown;
  validateEdge(edge: unknown, source: unknown, target: unknown): unknown;
  validateGraph(cell: unknown, context: number): unknown;
  getCellValidationError(cell: unknown): unknown;
  validateCell(cell: unknown, context: number): unknown;
  getBackgroundImage(...args: any[]): unknown;
  setBackgroundImage(image: unknown): void;
  getFoldingImage(state: unknown): unknown;
  convertValueToString(cell: unknown): unknown;
  getLabel(cell: unknown): unknown;
  isHtmlLabel(cell: unknown): unknown;
  isHtmlLabels(...args: any[]): unknown;
  setHtmlLabels(value: unknown): void;
  isWrapping(cell: unknown): boolean;
  isLabelClipped(cell: unknown): boolean;
  getTooltip(state: unknown, node: unknown, x: number, y: number): unknown;
  getLinkForCell(cell: unknown): unknown;
  getCursorForMouseEvent(me: unknown): unknown;
  getCursorForCell(cell: unknown): unknown;
  getStartSize(swimlane: unknown, ignoreState: unknown): unknown;
  getSwimlaneDirection(style: number): unknown;
  getActualStartSize(swimlane: unknown, ignoreState: unknown): unknown;
  getImage(state: unknown): unknown;
  isTransparentState(state: unknown): boolean;
  getVerticalAlign(state: unknown): unknown;
  getIndicatorColor(state: unknown): unknown;
  getIndicatorGradientColor(state: unknown): unknown;
  getIndicatorShape(state: unknown): unknown;
  getIndicatorImage(state: unknown): unknown;
  getBorder(...args: any[]): unknown;
  setBorder(value: unknown): void;
  isSwimlane(cell: unknown, ignoreState: unknown): boolean;
  isResizeContainer(...args: any[]): unknown;
  setResizeContainer(value: unknown): void;
  isEnabled(...args: any[]): boolean;
  setEnabled(value: unknown): void;
  isEscapeEnabled(...args: any[]): unknown;
  setEscapeEnabled(value: unknown): void;
  isInvokesStopCellEditing(...args: any[]): unknown;
  setInvokesStopCellEditing(value: unknown): void;
  isEnterStopsCellEditing(...args: any[]): unknown;
  setEnterStopsCellEditing(value: unknown): void;
  isCellLocked(cell: unknown): boolean;
  isCellsLocked(...args: any[]): boolean;
  setCellsLocked(value: unknown): void;
  getCloneableCells(cells: unknown): unknown;
  isCellCloneable(cell: unknown): boolean;
  isCellsCloneable(...args: any[]): unknown;
  setCellsCloneable(value: unknown): void;
  getExportableCells(cells: unknown): unknown;
  canExportCell(cell: unknown): unknown;
  getImportableCells(cells: unknown): unknown;
  canImportCell(cell: unknown): unknown;
  isCellSelectable(cell: unknown): unknown;
  isCellsSelectable(...args: any[]): unknown;
  setCellsSelectable(value: unknown): void;
  getDeletableCells(cells: unknown): unknown;
  isCellDeletable(cell: unknown): boolean;
  isCellsDeletable(...args: any[]): unknown;
  setCellsDeletable(value: unknown): void;
  isLabelMovable(cell: unknown): boolean;
  isCellRotatable(cell: unknown): boolean;
  getMovableCells(cells: unknown): unknown;
  isCellMovable(cell: unknown): unknown;
  isCellsMovable(...args: any[]): unknown;
  setCellsMovable(value: unknown): void;
  isGridEnabled(...args: any[]): unknown;
  setGridEnabled(value: unknown): void;
  isPortsEnabled(...args: any[]): unknown;
  setPortsEnabled(value: unknown): void;
  getGridSize(...args: any[]): unknown;
  setGridSize(value: unknown): void;
  getTolerance(...args: any[]): unknown;
  setTolerance(value: unknown): void;
  isVertexLabelsMovable(...args: any[]): unknown;
  setVertexLabelsMovable(value: unknown): void;
  isEdgeLabelsMovable(...args: any[]): unknown;
  setEdgeLabelsMovable(value: unknown): void;
  isSwimlaneNesting(...args: any[]): unknown;
  setSwimlaneNesting(value: unknown): void;
  isSwimlaneSelectionEnabled(...args: any[]): unknown;
  setSwimlaneSelectionEnabled(value: unknown): void;
  isMultigraph(...args: any[]): unknown;
  setMultigraph(value: unknown): void;
  isAllowLoops(...args: any[]): unknown;
  setAllowDanglingEdges(value: unknown): void;
  isAllowDanglingEdges(...args: any[]): unknown;
  setConnectableEdges(value: unknown): void;
  isConnectableEdges(...args: any[]): unknown;
  setCloneInvalidEdges(value: unknown): void;
  isCloneInvalidEdges(...args: any[]): unknown;
  setAllowLoops(value: unknown): void;
  isDisconnectOnMove(...args: any[]): unknown;
  setDisconnectOnMove(value: unknown): void;
  isDropEnabled(...args: any[]): unknown;
  setDropEnabled(value: unknown): void;
  isSplitEnabled(...args: any[]): unknown;
  setSplitEnabled(value: unknown): void;
  isCellResizable(cell: unknown): boolean;
  isCellsResizable(...args: any[]): unknown;
  setCellsResizable(value: unknown): void;
  isTerminalPointMovable(cell: unknown, source: unknown): boolean;
  isCellBendable(cell: unknown): unknown;
  isCellsBendable(...args: any[]): unknown;
  setCellsBendable(value: unknown): void;
  isCellEditable(cell: unknown): unknown;
  isCellsEditable(...args: any[]): unknown;
  setCellsEditable(value: unknown): void;
  isCellDisconnectable(cell: unknown, terminal: unknown, source: unknown): unknown;
  isCellsDisconnectable(...args: any[]): unknown;
  setCellsDisconnectable(value: unknown): void;
  isValidSource(cell: unknown): boolean;
  isValidTarget(cell: unknown): unknown;
  isValidConnection(source: unknown, target: unknown): boolean;
  setConnectable(connectable: unknown): void;
  isConnectable(...args: any[]): boolean;
  setTooltips(enabled: boolean): void;
  setPanning(enabled: boolean): void;
  isEditing(cell: unknown): boolean;
  isAutoSizeCell(cell: unknown): boolean;
  isAutoSizeCells(...args: any[]): unknown;
  setAutoSizeCells(value: unknown): void;
  isExtendParent(cell: unknown): unknown;
  isExtendParents(...args: any[]): unknown;
  setExtendParents(value: unknown): void;
  isExtendParentsOnAdd(cell: unknown): unknown;
  setExtendParentsOnAdd(value: unknown): void;
  isExtendParentsOnMove(...args: any[]): unknown;
  setExtendParentsOnMove(value: unknown): void;
  isRecursiveResize(state: unknown): unknown;
  setRecursiveResize(value: unknown): void;
  isConstrainChild(cell: unknown): boolean;
  isConstrainChildren(...args: any[]): unknown;
  setConstrainChildren(value: unknown): void;
  isConstrainRelativeChildren(...args: any[]): unknown;
  setConstrainRelativeChildren(value: unknown): void;
  isAllowNegativeCoordinates(...args: any[]): unknown;
  setAllowNegativeCoordinates(value: unknown): void;
  getOverlap(cell: unknown): boolean;
  isAllowOverlapParent(cell: unknown): boolean;
  getFoldableCells(cells: unknown, collapse: unknown): unknown;
  isCellFoldable(cell: unknown, collapse: unknown): boolean;
  isValidDropTarget(cell: unknown, cells: unknown, evt: unknown): unknown;
  isSplitTarget(target: unknown, cells: unknown, evt: unknown): boolean;
  getDropTarget(cells: unknown, evt: unknown, cell: unknown, clone: unknown): boolean;
  getDefaultParent(...args: any[]): unknown;
  setDefaultParent(cell: unknown): void;
  getSwimlane(cell: unknown): unknown;
  getSwimlaneAt(x: number, y: number, parent: unknown): unknown;
  getCellAt(x: number, y: number, parent: unknown, vertices: unknown, edges: unknown, ignoreFn: unknown): boolean;
  intersects(state: unknown, x: number, y: number): unknown;
  hitsSwimlaneContent(swimlane: unknown, x: number, y: number): boolean;
  getChildVertices(parent: unknown): unknown;
  getChildEdges(parent: unknown): unknown;
  getChildCells(parent: unknown, vertices: unknown, edges: unknown): unknown;
  getConnections(cell: unknown, parent: unknown): unknown;
  getIncomingEdges(cell: unknown, parent: unknown): unknown;
  getOutgoingEdges(cell: unknown, parent: unknown): unknown;
  getEdges(cell: unknown, parent: unknown, incoming: unknown, outgoing: unknown, includeLoops: unknown, recurse: unknown): unknown;
  isValidAncestor(cell: unknown, parent: unknown, recurse: unknown): unknown;
  getOpposites(edges: unknown, terminal: unknown, sources: unknown, targets: unknown): unknown;
  getEdgesBetween(source: unknown, target: unknown, directed: unknown): unknown;
  getPointForEvent(evt: unknown, addOffset: unknown): unknown;
  getCells(x: number, y: number, width: number, height: number, parent: unknown, result: unknown): unknown;
  getCellsBeyond(x0: number, y0: number, parent: unknown, rightHalfpane: number, bottomHalfpane: number): unknown;
  findTreeRoots(parent: unknown, isolate: boolean, invert: unknown): unknown;
  traverse(vertex: number, directed: unknown, func: unknown, edge: unknown, visited: boolean, inverse: unknown): boolean;
  isCellSelected(cell: unknown): boolean;
  isSelectionEmpty(...args: any[]): boolean;
  clearSelection(...args: any[]): void;
  getSelectionCount(...args: any[]): unknown;
  getSelectionCell(...args: any[]): unknown;
  getSelectionCells(...args: any[]): unknown;
  setSelectionCell(cell: unknown): void;
  setSelectionCells(cells: unknown): void;
  addSelectionCell(cell: unknown): void;
  addSelectionCells(cells: unknown): void;
  removeSelectionCell(cell: unknown): void;
  removeSelectionCells(cells: unknown): void;
  selectRegion(rect: unknown, evt: unknown): unknown;
  selectNextCell(...args: any[]): unknown;
  selectPreviousCell(...args: any[]): unknown;
  selectParentCell(...args: any[]): unknown;
  selectChildCell(...args: any[]): unknown;
  selectCell(isNext: number, isParent: boolean, isChild: boolean): unknown;
  selectAll(parent: unknown, descendants: unknown): unknown;
  selectVertices(parent: unknown, selectGroups: unknown): unknown;
  selectEdges(parent: unknown): unknown;
  selectCells(vertices: unknown, edges: unknown, parent: unknown, selectGroups: unknown): unknown;
  selectCellForEvent(cell: unknown, evt: unknown): unknown;
  selectCellsForEvent(cells: unknown, evt: unknown): unknown;
  createHandler(state: unknown): unknown;
  createVertexHandler(state: unknown): unknown;
  createEdgeHandler(state: unknown, edgeStyle: number): unknown;
  createEdgeSegmentHandler(state: unknown): unknown;
  createElbowEdgeHandler(state: unknown): unknown;
  addMouseListener(listener: boolean): void;
  removeMouseListener(listener: boolean): void;
  updateMouseEvent(me: unknown, evtName: string): void;
  getStateForTouchEvent(evt: unknown): unknown;
  isEventIgnored(evtName: string, me: unknown, sender: unknown): boolean;
  isSyntheticEventIgnored(evtName: string, me: unknown, sender: unknown): unknown;
  isEventSourceIgnored(evtName: string, me: unknown): boolean;
  getEventState(state: unknown): unknown;
  fireMouseEvent(evtName: string, me: unknown, sender: unknown): unknown;
  consumeMouseEvent(evtName: string, me: unknown, sender: unknown): unknown;
  fireGestureEvent(evt: unknown, cell: unknown): unknown;
  destroy(...args: any[]): void;
}