// AUTO-GENERATED FROM JSDOC. DO NOT EDIT.
export declare class mxGraphModel {
  constructor(root: unknown);
  clear(...args: any[]): void;
  isCreateIds(...args: any[]): unknown;
  setCreateIds(value: unknown): void;
  createRoot(...args: any[]): unknown;
  getCell(id: number): unknown;
  filterCells(cells: unknown, filter: unknown): unknown;
  getDescendants(parent: unknown): unknown;
  filterDescendants(filter: unknown, parent: unknown): unknown;
  getRoot(cell: unknown): unknown;
  setRoot(root: unknown): void;
  rootChanged(root: unknown): unknown;
  isRoot(cell: unknown): unknown;
  isLayer(cell: unknown): unknown;
  isAncestor(parent: unknown, child: unknown): unknown;
  contains(cell: unknown): unknown;
  getParent(cell: unknown): unknown;
  add(parent: unknown, child: unknown, index: number): void;
  cellAdded(cell: unknown): unknown;
  createId(cell: unknown): unknown;
  updateEdgeParents(cell: unknown, root: unknown): void;
  updateEdgeParent(edge: unknown, root: unknown): void;
  getOrigin(cell: unknown): unknown;
  getNearestCommonAncestor(cell1: unknown, cell2: unknown): unknown;
  remove(cell: unknown): void;
  cellRemoved(cell: unknown): unknown;
  parentForCellChanged(cell: unknown, parent: unknown, index: number): unknown;
  getChildCount(cell: unknown): unknown;
  getChildAt(cell: unknown, index: number): unknown;
  getChildren(cell: unknown): unknown;
  getChildVertices(parent: unknown): unknown;
  getChildEdges(parent: unknown): unknown;
  getChildCells(parent: unknown, vertices: unknown, edges: unknown): unknown;
  getTerminal(edge: unknown, isSource: boolean): unknown;
  setTerminal(edge: unknown, terminal: unknown, isSource: boolean): void;
  setTerminals(edge: unknown, source: unknown, target: unknown): void;
  terminalForCellChanged(edge: unknown, terminal: unknown, isSource: boolean): unknown;
  getEdgeCount(cell: unknown): unknown;
  getEdgeAt(cell: unknown, index: number): unknown;
  getDirectedEdgeCount(cell: unknown, outgoing: unknown, ignoredEdge: unknown): unknown;
  getConnections(cell: unknown): unknown;
  getIncomingEdges(cell: unknown): unknown;
  getOutgoingEdges(cell: unknown): unknown;
  getEdges(cell: unknown, incoming: unknown, outgoing: unknown, includeLoops: unknown): unknown;
  getEdgesBetween(source: unknown, target: unknown, directed: unknown): unknown;
  getOpposites(edges: unknown, terminal: unknown, sources: unknown, targets: unknown): unknown;
  getTopmostCells(cells: unknown): unknown;
  isVertex(cell: unknown): unknown;
  isEdge(cell: unknown): unknown;
  isConnectable(cell: unknown): unknown;
  getValue(cell: unknown): unknown;
  setValue(cell: unknown, value: unknown): void;
  valueForCellChanged(cell: unknown, value: unknown): unknown;
  getGeometry(cell: unknown): unknown;
  setGeometry(cell: unknown, geometry: number): void;
  geometryForCellChanged(cell: unknown, geometry: number): unknown;
  getStyle(cell: unknown): unknown;
  setStyle(cell: unknown, style: number): void;
  styleForCellChanged(cell: unknown, style: number): unknown;
  isCollapsed(cell: unknown): unknown;
  setCollapsed(cell: unknown, collapsed: unknown): void;
  collapsedStateForCellChanged(cell: unknown, collapsed: unknown): unknown;
  isVisible(cell: unknown): unknown;
  setVisible(cell: unknown, visible: boolean): void;
  visibleStateForCellChanged(cell: unknown, visible: boolean): unknown;
  execute(change: unknown): unknown;
  beginUpdate(...args: any[]): unknown;
  endUpdate(...args: any[]): unknown;
  createUndoableEdit(significant: unknown): unknown;
  mergeChildren(from: unknown, to: unknown, cloneAllEdges: unknown): unknown;
  mergeChildrenImpl(from: unknown, to: unknown, cloneAllEdges: unknown, mapping: unknown): unknown;
  getParents(cells: unknown): unknown;
  cloneCell(cell: unknown, includeChildren: unknown): unknown;
  cloneCells(cells: unknown, includeChildren: unknown, mapping: unknown): unknown;
  cloneCellImpl(cell: unknown, mapping: unknown, includeChildren: unknown): unknown;
  cellCloned(cell: unknown): unknown;
  restoreClone(clone: unknown, cell: unknown, mapping: unknown): unknown;
}