// AUTO-GENERATED FROM JSDOC. DO NOT EDIT.
export declare class mxGraphHandler {
  constructor(graph: unknown);
  isEnabled(...args: any[]): unknown;
  setEnabled(value: unknown): void;
  isCloneEnabled(...args: any[]): unknown;
  setCloneEnabled(value: unknown): void;
  isMoveEnabled(...args: any[]): unknown;
  setMoveEnabled(value: unknown): void;
  isSelectEnabled(...args: any[]): unknown;
  setSelectEnabled(value: unknown): void;
  isRemoveCellsFromParent(...args: any[]): unknown;
  setRemoveCellsFromParent(value: unknown): void;
  isPropagateSelectionCell(cell: unknown, immediate: unknown, me: unknown): unknown;
  getInitialCellForEvent(me: unknown): unknown;
  isDelayedSelection(cell: unknown, me: unknown): unknown;
  selectDelayed(me: unknown): unknown;
  consumeMouseEvent(evtName: string, me: unknown): unknown;
  mouseDown(sender: unknown, me: unknown): unknown;
  getGuideStates(...args: any[]): unknown;
  getCells(initialCell: unknown): unknown;
  getPreviewBounds(cells: unknown): unknown;
  getBoundingBox(cells: unknown): unknown;
  createPreviewShape(bounds: unknown): unknown;
  start(cell: unknown, x: number, y: number, cells: unknown): void;
  addStates(cell: unknown, dict: unknown): void;
  isCellMoving(cell: unknown): unknown;
  useGuidesForEvent(me: unknown): unknown;
  snap(vector: unknown): unknown;
  getDelta(me: unknown): unknown;
  updateHint(me: unknown): void;
  removeHint(...args: any[]): void;
  roundLength(length: number): unknown;
  isValidDropTarget(target: unknown, me: unknown): unknown;
  checkPreview(...args: any[]): unknown;
  mouseMove(sender: unknown, me: unknown): unknown;
  updatePreview(remote: unknown): void;
  updatePreviewShape(...args: any[]): void;
  updateLivePreview(dx: number, dy: number): void;
  redrawHandles(states: unknown): void;
  resetPreviewStates(states: unknown): void;
  suspend(...args: any[]): unknown;
  resume(...args: any[]): unknown;
  resetLivePreview(...args: any[]): void;
  setHandlesVisibleForCells(cells: unknown, visible: boolean): void;
  setHighlightColor(color: string): void;
  mouseUp(sender: unknown, me: unknown): unknown;
  reset(...args: any[]): void;
  shouldRemoveCellsFromParent(parent: unknown, cells: unknown, evt: unknown): unknown;
  moveCells(cells: unknown, dx: number, dy: number, clone: unknown, target: unknown, evt: unknown): unknown;
  shouldRemoveParent(parent: unknown): unknown;
  destroyShapes(...args: any[]): void;
  destroy(...args: any[]): void;
}