// AUTO-GENERATED FROM JSDOC. DO NOT EDIT.
export declare class mxShape {
  constructor(stencil: unknown);
  init(container: unknown): unknown;
  initStyles(container: unknown): unknown;
  isParseVml(...args: any[]): unknown;
  isHtmlAllowed(...args: any[]): unknown;
  getSvgScreenOffset(...args: any[]): unknown;
  create(container: unknown): unknown;
  createSvg(...args: any[]): unknown;
  createVml(...args: any[]): unknown;
  createHtml(...args: any[]): unknown;
  reconfigure(...args: any[]): unknown;
  redraw(...args: any[]): void;
  clear(...args: any[]): void;
  updateBoundsFromPoints(...args: any[]): void;
  getLabelBounds(rect: unknown): unknown;
  getLabelMargins(rect: unknown): unknown;
  checkBounds(...args: any[]): unknown;
  createVmlGroup(...args: any[]): unknown;
  redrawShape(...args: any[]): void;
  createCanvas(...args: any[]): unknown;
  createSvgCanvas(...args: any[]): unknown;
  createVmlCanvas(...args: any[]): unknown;
  updateVmlContainer(...args: any[]): void;
  redrawHtmlShape(...args: any[]): void;
  updateHtmlFilters(node: unknown): void;
  updateHtmlColors(node: unknown): void;
  updateHtmlBounds(node: unknown): void;
  destroyCanvas(canvas: unknown): void;
  paint(c: unknown): unknown;
  configureCanvas(c: unknown, x: number, y: number, w: unknown, h: unknown): unknown;
  getGradientBounds(c: unknown, x: number, y: number, w: unknown, h: unknown): unknown;
  updateTransform(c: unknown, x: number, y: number, w: unknown, h: unknown): void;
  paintVertexShape(c: unknown, x: number, y: number, w: unknown, h: unknown): unknown;
  paintBackground(c: unknown, x: number, y: number, w: unknown, h: unknown): unknown;
  paintForeground(c: unknown, x: number, y: number, w: unknown, h: unknown): unknown;
  paintEdgeShape(c: unknown, pts: unknown): unknown;
  getArcSize(w: unknown, h: unknown): unknown;
  paintGlassEffect(c: unknown, x: number, y: number, w: unknown, h: unknown, arc: unknown): unknown;
  addPoints(c: unknown, pts: unknown, rounded: unknown, arcSize: number, close: unknown, exclude: number, initialMove: unknown): void;
  resetStyles(...args: any[]): void;
  apply(state: unknown): unknown;
  setCursor(cursor: unknown): void;
  getCursor(...args: any[]): unknown;
  isRoundable(...args: any[]): unknown;
  updateBoundingBox(...args: any[]): void;
  createBoundingBox(...args: any[]): unknown;
  augmentBoundingBox(bbox: number): unknown;
  isPaintBoundsInverted(...args: any[]): unknown;
  getRotation(...args: any[]): unknown;
  getTextRotation(...args: any[]): unknown;
  getShapeRotation(...args: any[]): unknown;
  createTransparentSvgRectangle(x: number, y: number, w: unknown, h: unknown): unknown;
  setTransparentBackgroundImage(node: unknown): void;
  releaseSvgGradients(grads: unknown): unknown;
  destroy(...args: any[]): void;
}