// AUTO-GENERATED FROM JSDOC. DO NOT EDIT.
export declare class mxVertexHandler {
  constructor(state: unknown);
  init(...args: any[]): unknown;
  isRotationHandleVisible(...args: any[]): unknown;
  isConstrainedEvent(me: unknown): unknown;
  isCenteredEvent(state: unknown, me: unknown): unknown;
  createCustomHandles(...args: any[]): unknown;
  updateMinBounds(...args: any[]): void;
  getSelectionBounds(state: unknown): unknown;
  createParentHighlightShape(bounds: unknown): unknown;
  createSelectionShape(bounds: unknown): unknown;
  getSelectionColor(...args: any[]): unknown;
  getSelectionStrokeWidth(...args: any[]): unknown;
  isSelectionDashed(...args: any[]): unknown;
  createSizer(cursor: unknown, index: number, size: number, fillColor: string): unknown;
  isSizerVisible(index: number): unknown;
  createSizerShape(bounds: unknown, index: number, fillColor: string): unknown;
  moveSizerTo(shape: unknown, x: number, y: number): unknown;
  getHandleForEvent(me: unknown): unknown;
  isCustomHandleEvent(me: unknown): unknown;
  mouseDown(sender: unknown, me: unknown): unknown;
  isLivePreviewBorder(...args: any[]): unknown;
  start(x: number, y: number, index: number): void;
  createGhostPreview(...args: any[]): unknown;
  setHandlesVisible(visible: boolean): void;
  hideSizers(...args: any[]): void;
  checkTolerance(me: unknown): unknown;
  updateHint(me: unknown): void;
  removeHint(...args: any[]): void;
  roundAngle(angle: unknown): unknown;
  roundLength(length: number): unknown;
  mouseMove(sender: unknown, me: unknown): unknown;
  isGhostPreview(...args: any[]): unknown;
  moveLabel(me: unknown): unknown;
  rotateVertex(me: unknown): unknown;
  resizeVertex(me: unknown): unknown;
  updateLivePreview(me: unknown): void;
  moveToFront(...args: any[]): unknown;
  mouseUp(sender: unknown, me: unknown): unknown;
  isRecursiveResize(state: unknown, me: unknown): unknown;
  rotateClick(...args: any[]): unknown;
  rotateCell(cell: unknown, angle: unknown, parent: unknown): unknown;
  reset(...args: any[]): void;
  resizeCell(cell: unknown, dx: number, dy: number, index: number, gridEnabled: number, constrained: unknown, recurse: unknown): unknown;
  moveChildren(cell: unknown, dx: number, dy: number): unknown;
  union(bounds: unknown, dx: number, dy: number, index: number, gridEnabled: number, scale: number, tr: unknown, constrained: unknown): unknown;
  redraw(ignoreHandles: unknown): void;
  getHandlePadding(...args: any[]): unknown;
  getSizerBounds(...args: any[]): unknown;
  redrawHandles(...args: any[]): void;
  isCustomHandleVisible(handle: unknown): unknown;
  getRotationHandlePosition(...args: any[]): unknown;
  isParentHighlightVisible(...args: any[]): unknown;
  updateParentHighlight(...args: any[]): void;
  drawPreview(...args: any[]): unknown;
  getSelectionBorderBounds(...args: any[]): unknown;
  destroy(...args: any[]): void;
}